server:
  port: 8082

#MYSQL
spring:
# kafka
  kafka:
    bootstrapServers: 192.168.72.128:9092
#    生产者
    producer:
      retries: 0
##        每次发送消息的量
      batchSize: 16384
      bufferMemory: 33554432
      keySerializer: org.apache.kafka.common.serialization.StringSerializer
      valueSerializer: org.apache.kafka.common.serialization.StringSerializer

    #  制定默认消费者group id
    consumer:
      groupId: consumer-group
      autoOffsetReset: earliest
      enableAutoCommit: true
      autoCommitInterval: 1000
      keySerializer: org.apache.kafka.common.serialization.StringSerializer
      valueSerializer: org.apache.kafka.common.serialization.StringSerializer
  datasource:
    url: jdbc:mysql://192.168.72.128:8066/TESTDB
#    url: jdbc:mysql://192.168.72.128:3306/db01
    username: root
    password: 123456
    druid:
      driverClassName: com.mysql.jdbc.Driver

#spring.jpa.show-sql=true
#  jpa:
#    show-sql: false
#    hibernate:
#      naming:
#        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
#      ddl-auto: update

  application:
    name: task-manager-api

#默认支持文件上传.
  http:
    multipart:
      enabled: true
#支持文件写入磁盘.
      fileSizeThreshold: 0
# 上传文件的临时目录
      location: C:\workSpace3\task-manager\task-manager-api\src\main\resources\image
# 最大支持文件大小
      max-file-size: 5Mb
# 最大支持请求大小
      max-request-size: 10Mb

#mybatis&&通用Mapper
mybatis:
  type-aliases-package: com.cn.taskManager.model
#  mapper-locations: classpath*:mapper/*.xml
  mapper-locations: classpath:/mapper/*Mapper.xml
  configuration:
  # 开启驼峰去掉“_”
    mapUnderscoreToCamelCase: true
#注册中心地址
eureka:
  client:
    serviceUrl:
#      defaultZone: ${eureka.client.serviceUrl.defaultZone}
      defaultZone: http://localhost:8090/eureka/
  healthcheck:
    enabled: true
  instance:
    lease-expiration-duration-in-seconds: 30
    lease-renewal-interval-in-seconds: 10

swagger2:
  enable: true
#    redis:
#      #数据库索引
#      database: 0
#      host: 127.0.0.1
#      port: 6379
#      password: 123456
#      jedis:
#        pool:
#          #最大连接数
#          max-active: 8
#          #最大阻塞等待时间(负数表示没限制)
#          max-wait: -1
#          #最大空闲
#          max-idle: 8
#          #最小空闲
#          min-idle: 0
#      #连接超时时间
#      timeout: 10000



