server:
  port: 8091
spring:
  application:
    name: task-manager-config
  cloud:
    config:
#      discovery:
#        enabled: true
#        serviceId: task-manager-config
      server:
        git:
          uri: https://github.com/bhsdy/config/
          search-paths: bhsdy
          username: bhsdy1024@163.com
          password: bhsdy1024
      label: master
eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8090/eureka/